### ISSUE TITLE
GridPro throws typerror when clicking within Grid nut not on a row

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-grid-pro-flow#57] opened 2019-06-05 09:14 UTC
@Braus commented on [Wed Jun 05 2019](https://github.com/vaadin/flow/issues/5845)

Hi everyone,

I'm using GridPro, but I had to swap it with a normal Grid because GridPro is sensitive to throw typerrors as seen in the attached image. This bug occurs either when I click the GridPro many times or when I click below the last row in the grid.

I create the GridPro using java.

![image](https://user-images.githubusercontent.com/48833301/58944783-cad58580-8782-11e9-8bd0-a65fd05a15b1.png)

**Comment by pekam** [comment] 2019-06-05 09:49
Closing as a duplicate of https://github.com/vaadin/vaadin-grid-pro/issues/89

The issue has been fixed and released in web component version 2.0.1, included in the Flow component version 2.0 (currently released only as a pre-release), which will be included in Vaadin 14.

**Closed by pekam** 2019-06-05 09:49 UTC
